trigger:
- master

name: $(Rev:r)
steps:

  - pwsh: |
      $Version = "1.0.{0}" -f $env:BUILD_BUILDNUMBER
      Write-Output ("release version: {0}" -f $Version)
      Install-Module Az.Storage -Force
      Update-ModuleManifest -Path ./AzureDevopsDataCollector/AzureDevopsDataCollector.psd1 -ModuleVersion $Version
      Publish-Module -Name ./AzureDevopsDataCollector -NuGetApiKey $env:PSGALLERYAPIKEY
    displayName: Publish to powershell gallery
    name: publish
    workingDirectory: $(build.sourcesDirectory)
    failOnStderr: true
    env:
      PSGALLERYAPIKEY: $(psgalleryapikey)